# Generated by Django 4.2.6 on 2023-11-20 15:12

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                default="post/default.jpg",
                null=True,
                upload_to=post.models.Post.image_directory_path,
            ),
        ),
    ]
