# Generated by Django 4.2.6 on 2023-11-20 07:50

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_user_firebase_uid_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile",
            field=models.ImageField(
                blank=True,
                default="profile/default.png",
                upload_to=accounts.models.User.profile_directory_path,
                verbose_name="프로필 사진",
            ),
        ),
    ]
