# Generated by Django 4.2.6 on 2023-11-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=10)),
                ("change", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "change_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("market_cap", models.DecimalField(decimal_places=2, max_digits=15)),
                ("volume", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "Stocks",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("league", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Teams",
            },
        ),
    ]
