# Generated by Django 4.2.6 on 2023-11-05 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("team_info", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="name",
        ),
        migrations.AddField(
            model_name="stock",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="team_info.team",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
