# Generated by Django 4.2.6 on 2023-11-26 08:51

from django.db import migrations, models
import django.db.models.deletion
import team_info.models


class Migration(migrations.Migration):
    dependencies = [
        ("team_info", "0002_match_player_stadium"),
    ]

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("api_id", models.SmallIntegerField()),
            ],
            options={
                "verbose_name_plural": "Leagues",
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("surface", models.CharField(max_length=255)),
                ("capacity", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name_plural": "Venues",
            },
        ),
        migrations.DeleteModel(
            name="Stadium",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="league",
            new_name="code",
        ),
        migrations.AddField(
            model_name="match",
            name="team",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_info",
                to="team_info.team",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="match",
            name="venue",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_venue",
                to="team_info.team",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="team",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_info",
                to="team_info.team",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="country",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="founded",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="national",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="player",
            name="photo",
            field=models.ImageField(
                upload_to=team_info.models.Player.player_directory_path
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="team",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="venue_info",
                to="team_info.team",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="team",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_info",
                to="team_info.league",
            ),
            preserve_default=False,
        ),
    ]
