# Generated by Django 4.2.6 on 2023-11-05 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("team_info", "0002_remove_stock_name_stock_team_alter_team_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="team",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_info",
                to="team_info.team",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
