# Generated by Django 4.2.6 on 2023-11-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "team_info",
            "0003_league_venue_delete_stadium_rename_league_team_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="api_id",
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
