# Generated by Django 4.2.6 on 2023-11-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team_info", "0004_alter_stock_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="price_unit",
            field=models.CharField(default="USD", max_length=20),
            preserve_default=False,
        ),
    ]
