# Generated by Django 4.2.6 on 2023-11-26 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team_info", "0004_team_api_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="country",
        ),
    ]
