# Generated by Django 4.2.6 on 2023-11-26 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("team_info", "0005_remove_team_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_info",
                to="team_info.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_venue",
                to="team_info.team",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_info",
                to="team_info.team",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_info",
                to="team_info.league",
            ),
        ),
    ]
