# Generated by Django 4.2.6 on 2023-11-26 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "team_info",
            "0006_alter_match_team_alter_match_venue_alter_player_team_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="team",
            new_name="league",
        ),
    ]
