# Generated by Django 4.2.6 on 2023-11-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team_info", "0008_player_api_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="detailed_position",
        ),
        migrations.RemoveField(
            model_name="player",
            name="nationality",
        ),
        migrations.AddField(
            model_name="player",
            name="age",
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
