# Generated by Django 4.2.6 on 2023-11-26 15:37

from django.db import migrations, models
import team_info.models


class Migration(migrations.Migration):
    dependencies = [
        ("team_info", "0010_remove_player_age_player_detailed_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to=team_info.models.Player.player_directory_path
            ),
        ),
    ]
