# Generated by Django 4.2.6 on 2023-11-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team_info", "0011_alter_player_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="number",
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
