# Generated by Django 4.2.6 on 2023-11-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team_info", "0012_player_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="number",
            field=models.SmallIntegerField(null=True),
        ),
    ]
