# Generated by Django 4.2.6 on 2023-11-27 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("team_info", "0013_alter_player_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team", models.CharField(max_length=255)),
                ("season_year", models.IntegerField()),
                ("matches_played", models.IntegerField()),
                ("wins", models.IntegerField()),
                ("draws", models.IntegerField()),
                ("loses", models.IntegerField()),
                ("goals_for", models.IntegerField()),
                ("goals_against", models.IntegerField()),
                ("goal_difference", models.IntegerField()),
                ("points", models.IntegerField()),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="team_info.league",
                    ),
                ),
            ],
        ),
    ]
