# Generated by Django 4.2.6 on 2023-11-28 04:20

from django.db import migrations, models
import django.db.models.deletion
import team_info.models


class Migration(migrations.Migration):
    dependencies = [
        ("team_info", "0014_seasondata"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("published_date", models.DateTimeField()),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, upload_to=team_info.models.News.news_directory_path
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="team_info.team"
                    ),
                ),
            ],
        ),
    ]
