# Generated by Django 4.2.6 on 2023-11-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team_info", "0015_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="thumbnail",
            field=models.URLField(blank=True),
        ),
    ]
