# Generated by Django 4.2.6 on 2023-11-28 06:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team_info", "0016_alter_news_thumbnail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="company",
            new_name="author",
        ),
    ]
